export const INIT_SUGGEST_VIDEOS = 'INIT_SUGGEST_VIDEOS';
export const SUGGEST_VIDEO_SUCCESS = 'SUGGEST_VIDEO_SUCCESS';
export const SUGGEST_VIDEO_FAIL = 'SUGGEST_VIDEO_FAIL';
export const SEARCH_QUERY_UPDATED = 'SEARCH_QUERY_UPDATED';
export const FILE_URL_CHANGED = 'FILE_URL_CHANGED';
export const VIDEO_UPLOADED_FOR_PROCESSING = 'VIDEO_UPLOADED_FOR_PROCESSING';
export const VIDEO_URL_INCORRECT = 'VIDEO_URL_INCORRECT';
