export const INIT_SUGGEST_VIDEOS = 'INIT_SUGGEST_VIDEOS';
export const SUGGEST_VIDEO_SUCCESS = 'SUGGEST_VIDEO_SUCCESS';
export const SUGGEST_VIDEO_FAIL = 'SUGGEST_VIDEO_FAIL';
export const SEARCH_QUERY_UPDATED = 'SEARCH_QUERY_UPDATED';

